<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <?= $this->include('utils/css'); ?>
  <title>admin panel</title>
</head>

<body>
  <?= $this->include('component/admin/header'); ?>

  <main class="w-full flex flex-row relative mt-14">
    <?= $this->include('component/admin/aside'); ?>
    <div class="flex-none md:px-8 px-4 pt-8 bg-indigo-400 md:translate-x-60 w-full md:w-[calc(100%-240px)]">
      <h1 class="text-2xl font-medium leading-7 text-slate-800 ">Dashbaord</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aperiam saepe quas a ratione tempora, ab suscipit, minus, rem doloremque itaque vel molestiae quis sapiente. Consequatur necessitatibus reprehenderit voluptas quo ab optio voluptatum exercitationem praesentium voluptatibus ipsum, facilis velit minima pariatur veniam tenetur fuga! Iste dolore sunt, non odio enim dolor vel nemo adipisci fuga quis reprehenderit saepe et dignissimos minima in quam consequuntur tempora magnam deleniti velit quae. Qui voluptates perferendis harum iure vel at ut tempore sunt amet illum. Ratione sequi quas inventore distinctio delectus ut ducimus fugit suscipit ipsam optio corporis voluptatem nobis, molestiae, quia architecto modi sed debitis dolores sapiente omnis veniam sint accusantium. Rem tempora laudantium nisi dolore nihil voluptates perferendis, fugit nulla ad optio dolor unde eius at sequi nobis cum cumque adipisci cupiditate, sapiente deleniti, voluptatibus similique esse quos! Ipsa adipisci accusantium ipsum deserunt quia recusandae, non dolores, rem magnam repellendus omnis modi numquam sunt? Pariatur, nam reiciendis. Harum id, officia at corporis fugit possimus fuga tenetur rem maiores, optio, odit cumque numquam nemo asperiores enim reprehenderit dolorem magnam voluptates aliquid nisi? Nemo, mollitia dicta ipsam alias odit dignissimos voluptatum provident, numquam sapiente eos corporis aliquid autem expedita iste iure pariatur eius laborum illo harum, nam neque eum assumenda. Dicta velit aliquam, possimus laborum ad tempore eligendi, corporis tempora iure delectus ratione dolore magnam odio quia ea ut! Recusandae non adipisci perferendis iusto, ipsum porro repellendus molestiae quia nemo fugiat facere blanditiis quae odit a quaerat quos ab possimus beatae nostrum est sit ipsa optio. Sequi dolore consequuntur alias repudiandae voluptates tenetur magni provident odit ratione veniam asperiores ipsa natus ex totam perferendis, quia, rem excepturi, omnis at et officia quisquam magnam. Voluptatibus voluptatum repellat mollitia, qui dolorum itaque labore. Tempora, aspernatur voluptatibus quae aliquid delectus possimus ullam. Porro tempore quos nobis impedit dicta.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aperiam saepe quas a ratione tempora, ab suscipit, minus, rem doloremque itaque vel molestiae quis sapiente. Consequatur necessitatibus reprehenderit voluptas quo ab optio voluptatum exercitationem praesentium voluptatibus ipsum, facilis velit minima pariatur veniam tenetur fuga! Iste dolore sunt, non odio enim dolor vel nemo adipisci fuga quis reprehenderit saepe et dignissimos minima in quam consequuntur tempora magnam deleniti velit quae. Qui voluptates perferendis harum iure vel at ut tempore sunt amet illum. Ratione sequi quas inventore distinctio delectus ut ducimus fugit suscipit ipsam optio corporis voluptatem nobis, molestiae, quia architecto modi sed debitis dolores sapiente omnis veniam sint accusantium. Rem tempora laudantium nisi dolore nihil voluptates perferendis, fugit nulla ad optio dolor unde eius at sequi nobis cum cumque adipisci cupiditate, sapiente deleniti, voluptatibus similique esse quos! Ipsa adipisci accusantium ipsum deserunt quia recusandae, non dolores, rem magnam repellendus omnis modi numquam sunt? Pariatur, nam reiciendis. Harum id, officia at corporis fugit possimus fuga tenetur rem maiores, optio, odit cumque numquam nemo asperiores enim reprehenderit dolorem magnam voluptates aliquid nisi? Nemo, mollitia dicta ipsam alias odit dignissimos voluptatum provident, numquam sapiente eos corporis aliquid autem expedita iste iure pariatur eius laborum illo harum, nam neque eum assumenda. Dicta velit aliquam, possimus laborum ad tempore eligendi, corporis tempora iure delectus ratione dolore magnam odio quia ea ut! Recusandae non adipisci perferendis iusto, ipsum porro repellendus molestiae quia nemo fugiat facere blanditiis quae odit a quaerat quos ab possimus beatae nostrum est sit ipsa optio. Sequi dolore consequuntur alias repudiandae voluptates tenetur magni provident odit ratione veniam asperiores ipsa natus ex totam perferendis, quia, rem excepturi, omnis at et officia quisquam magnam. Voluptatibus voluptatum repellat mollitia, qui dolorum itaque labore. Tempora, aspernatur voluptatibus quae aliquid delectus possimus ullam. Porro tempore quos nobis impedit dicta.</p>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Aperiam saepe quas a ratione tempora, ab suscipit, minus, rem doloremque itaque vel molestiae quis sapiente. Consequatur necessitatibus reprehenderit voluptas quo ab optio voluptatum exercitationem praesentium voluptatibus ipsum, facilis velit minima pariatur veniam tenetur fuga! Iste dolore sunt, non odio enim dolor vel nemo adipisci fuga quis reprehenderit saepe et dignissimos minima in quam consequuntur tempora magnam deleniti velit quae. Qui voluptates perferendis harum iure vel at ut tempore sunt amet illum. Ratione sequi quas inventore distinctio delectus ut ducimus fugit suscipit ipsam optio corporis voluptatem nobis, molestiae, quia architecto modi sed debitis dolores sapiente omnis veniam sint accusantium. Rem tempora laudantium nisi dolore nihil voluptates perferendis, fugit nulla ad optio dolor unde eius at sequi nobis cum cumque adipisci cupiditate, sapiente deleniti, voluptatibus similique esse quos! Ipsa adipisci accusantium ipsum deserunt quia recusandae, non dolores, rem magnam repellendus omnis modi numquam sunt? Pariatur, nam reiciendis. Harum id, officia at corporis fugit possimus fuga tenetur rem maiores, optio, odit cumque numquam nemo asperiores enim reprehenderit dolorem magnam voluptates aliquid nisi? Nemo, mollitia dicta ipsam alias odit dignissimos voluptatum provident, numquam sapiente eos corporis aliquid autem expedita iste iure pariatur eius laborum illo harum, nam neque eum assumenda. Dicta velit aliquam, possimus laborum ad tempore eligendi, corporis tempora iure delectus ratione dolore magnam odio quia ea ut! Recusandae non adipisci perferendis iusto, ipsum porro repellendus molestiae quia nemo fugiat facere blanditiis quae odit a quaerat quos ab possimus beatae nostrum est sit ipsa optio. Sequi dolore consequuntur alias repudiandae voluptates tenetur magni provident odit ratione veniam asperiores ipsa natus ex totam perferendis, quia, rem excepturi, omnis at et officia quisquam magnam. Voluptatibus voluptatum repellat mollitia, qui dolorum itaque labore. Tempora, aspernatur voluptatibus quae aliquid delectus possimus ullam. Porro tempore quos nobis impedit dicta.</p>
    </div>
  </main>
  <script src="<?= base_url(); ?>template/dist/js/hidemenu.js"></script>
</body>

</html>